import { PostSearch } from "@/components/PostSearch";
import { Posts } from "@/components/Posts";
import { Metadata } from "next"


export const metadata: Metadata = {
	title: 'Blog | Next App',
	description: 'Generated by create next app',
}

export default function Blog() {
  
	return (
		<>
        	<h1>Blog Page</h1>
			<PostSearch/>
			<Posts/>
		</>
	)
}

